// Online Java Compiler
// Use this editor to write, compile and run your Java code online

class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
   
    
    //Declaração das Variáveis aqui
    
    String Nomealuno;
    double Nota1;
    double Nota2;
    String Raaluno;
    double Media;
    boolean true || false;
    char 'M';
    int Idade;
    double Medidade;
    String Nomeprofessor;
