// Online Java Compiler
// Use this editor to write, compile and run your Java code online

class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
   
    
    //Declaração das Variáveis aqui
    
    String nomealuno;
    double nota1;
    double nota2;
    String raaluno;
    double media;
    boolean true || false;
    char 'M';
    int idade;
    double medidade;
    String nomeprofessor;
