// Online Java Compiler
// Use this editor to write, compile and run your Java code online

public class Main {
    public static void main(String[] args) {

String nome1 = "Iphone 15 Pro";
String nome2 = "Notebook Acer Nitro 5";
String nome3 = "Fone de Ouvido Xiaomi Redmi Buds 4 Lite";

String marca1 = "Apple";
String marca2 = "Acer";
String marca3 = "Xiaomi";

    double preco1 = 6649.50;
    double preco2 = 4299.14;
    double preco3 = 134.90;

    int estoque1 = 35;
    int estoque2 = 20;
    int estoque3 = 12;

        System.out.println("Dados do Smartphone:");
        System.out.println("Nome: " + nome1);
        System.out.println("Marca: " + marca1);   
        System.out.println("Valor: " + preco1);   
        System.out.println("Quantidade: " + estoque1 +"\n");
    
        System.out.println("Dados do Laptop:");
        System.out.println("Nome: " + nome2);
        System.out.println("Marca: " + marca2);   
        System.out.println("Valor: " + preco2);   
        System.out.println("Quantidade: " + estoque2 +"\n");   
           
        System.out.println("Dados do Fone de Ouvido Bluetooth:");
        System.out.println("Nome: " + nome3);
        System.out.println("Marca: " + marca3);   
        System.out.println("Valor: " + preco3);   
        System.out.println("Quantidade: " + estoque3); 
    }
}
